cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:part_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:part_id>/',views.cart_remove,name='cart_remove'),
]

happyCarAuto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('cart/',include('cart.urls',namespace='cart')),
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path, include

app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('parts/', views.ProductListView.as_view(), name='Parts'),
    path('parts/<int:id>/',views.product_detail,name='product_detail'),
    path('categories/',views.CategorylistView.as_view(), name='categories'),
    path('categories/<int:id>',views.category_detail.as_view(),name='category_detail'),
    path('edit/', views.profile, name='profile'),
    path('newsletter/', include('newsletter.urls')),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PART_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PART_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False, initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from shop.models import Part
from .forms import CartAddProductForm

@require_POST
def cart_add(request,part_id):
    cart = Cart(request)
    part = get_object_or_404(Part, id=part_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(part=part, quantity=cd['quantity'], override_quantity=cd['override'])

    return redirect ('cart:cart_detail')


def cart_remove(request,part_id):
    cart = Cart(request)
    part = get_object_or_404(Part, id=part_id)
    cart.remove(part)

    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request,'cart/detail.html',{'cart':cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Shopping Cart
{% endblock %}

{% block content %}
<h1>Shopping Cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Part</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit Price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with part=item.part %}
    <tr>
        <td>{{ part.part_name }}</td>
        <td>{{ item.quantity }}</td>
        <td>
            <form action="{% url "cart:cart_remove" part.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
            </form>
        </td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
<p class="text-right">
    <a href="{% url "shop:home" %}" class="buttonlight">Continue Shopping</a>
    <a href="#" class="button">Checkout</a>
</p>
</table>
{% endblock %}