cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:part_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:part_id>/',views.cart_remove,name='cart_remove'),
]

happyCarAuto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('cart/',include('cart.urls',namespace='cart')),
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path, include

app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('parts/', views.ProductListView.as_view(), name='Parts'),
    path('parts/<int:id>/',views.product_detail,name='product_detail'),
    path('categories/',views.CategorylistView.as_view(), name='categories'),
    path('categories/<int:id>',views.category_detail.as_view(),name='category_detail'),
    path('edit/', views.profile, name='profile'),
    path('newsletter/', include('newsletter.urls')),
]

shop/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.

# Customer model

class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return '%s, %s' % (self.first_name, self.last_name)


# PartType model (aka Category)

class PartType(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/categories/%i/" % self.id



# Part model

class Part(models.Model):
    part_type = models.ForeignKey(PartType, related_name='parts', on_delete=models.CASCADE)
    part_name = models.CharField(max_length=200, db_index=True)
    part_number = models.CharField(max_length=50, db_index=True)
    part_description = models.TextField(blank=True)
    part_image = models.ImageField(upload_to='part_uploads/% Y/% m/% d/', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    availability = models.BooleanField(default=True)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.part_name)

    class Meta:
        ordering = ('part_name',)

    def get_absolute_url(self):
        return "/parts/%i/" % self.id


# define the Cart model
class Cart(models.Model):
    customer = models.ForeignKey(Customer, related_name='customer', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.customer)


# define the CartItem model used to store information about items in a cart
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='cart', on_delete=models.CASCADE)
    part = models.ForeignKey(Part, related_name='part', on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.part)

    class Meta:
        ordering = ('cart',)


# define the Order model
class Order(models.Model):
    order_number = models.AutoField(primary_key=True, )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    email = models.EmailField(max_length=250)
    shipping_address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    status = models.CharField(max_length=25,
                              choices=[('R', 'Received'), ('P', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered'),
                                       ('B', 'Back Order')], default='Received')
    comments = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.order_number)


# define the order items

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order', on_delete=models.CASCADE)
    part = models.ForeignKey(Part, related_name='order_part', on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.order)

class NewsLetterUsers(models.Model):
    email = models.EmailField()
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.email

shop/forms.py
from django import forms
from .models import Customer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = (
            'first_name', 'last_name', 'email', 'address', 'city', 'state', 'city', 'state', 'zipcode',
            'phone_number', 'created_date')


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']

shop/views.py
from .models import *
from django.shortcuts import render, redirect, get_object_or_404
from .forms import NewUserForm, UpdateUserForm
from django.contrib.auth import login
from django.contrib import messages
from django.views import generic
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required


now = timezone.now()


def home(request):
    return render(request, 'shop/home.html',
                  {'shop': home})


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("shop:home")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="registration/registration.html", context={"register_form": form})


class ProductListView(generic.ListView):
    model = Part

class CategorylistView(generic.ListView):
    model = PartType

class category_detail(generic.DetailView):
    model = PartType

def product_detail(request, id):
    product=get_object_or_404(Part,id=id,availability=True)
    cart_part_form = CartAddProductForm()
    return render(request,'shop/part/detail.html',{'part':product,'cart_part_form':cart_part_form})


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='/')
    else:
        user_form = UpdateUserForm(instance=request.user)

    return render(request, 'registration/profile.html', {'user_form': user_form})

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <title>HappyCar Auto</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                HappyCar Auto
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'shop:home' %}">Home</a></li>
                <li><a href="/parts">Part List</a></li>
               <li><a href="{% url 'shop:home' %}">Categories</a></li>
                <li><a href="{% url 'shop:home' %}">Your Account</a></li>
                <li><a href="{% url 'shop:profile' %}">Edit Profile</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
{#                                <img src="{% static "images/customer.jpg" %}" alt="customer"/>#}
                                <div class="caption">
                                    <h2>Column 1</h2>
                                    <p>Description for Column 1 </p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href=""
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
{#                                <img src="{% static "images/cupcakes.jpeg" %}" alt="cupcakes"/>#}
                                <div class="caption">
                                                                        <h2>Column 2</h2>
                                    <p>Description for column 2</p>
                                    <p><a class="btn btn-default" href=""
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
{#                                <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>#}
                                <div class="caption">
                                    <h2>Column 3</h2>
                                    <p>Description for column 3</p>
                                    <p><a class="btn btn-default" href="" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

shop/templates/shop/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
   <body>
   {% if user.is_authenticated %}
       <div class="page-container">

           <h2 class="top-menu">Hello {{ user.username }},</h2>
           <p>Please choose from below options.</p>
       </div>
   {% endif %}
   <div class="content container">
       <div class="row">
           <div class="col-md-12">
               <div class="links">
                   <!-- Example row of columns -->
                   <div class="row">
                       <div class="col-md-3">
                           <div class="thumbnail">
{#                               <img src="{% static "images/customer.jpg" %}" alt="customer"/>#}
                               <div class="caption">
                                   <h2>Our Parts</h2>
                                   <p>Take a look at all of the products in our store. We have a wide variety of parts available. Browse for yourself!</p>
                                   <p><a class="btn btn-primary" href="/parts"
                                         role="button">View
                                       Part List &raquo;</a></p>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
{#                               <img src="{% static "images/cupcakes.jpeg" %}" alt="cupcakes"/>#}
                               <div class="caption">
                                   <h2>Part Categories</h2>
                                   <p>Browse our parts by category. We have everything filtered so that you can look for a particular type of part!</p>
                                   <p><a class="btn btn-primary" href="/categories"
                                         role="button">View
                                       Categories &raquo;</a></p>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
{#                               <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>#}
                               <div class="caption">
                                   <h2>Your Account</h2>
                                   <p>View everything about your account! From order history to personal details, you can find it here.</p>
                                   <p><a class="btn btn-primary" href=""
                                         role="button">View Account &raquo;</a></p>
                               </div>
                           </div>
                       </div>

                   </div>
               </div>
           </div>
       </div>
   </div>
   </body>

{% endblock %}

</html>

shop/templates/shop/part_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
    <h1>Part List</h1>
    {% if part_list %}
        <ul>
        {% for part in part_list %}
            <li>
                <a href="{{ part.get_absolute_url }}">{{ part.part_name }}</a> - {{ part.part_description }}
            </li>
        </ul>
        {% endfor %}
    {% else %}
        <p>There are currently no parts in our shop.</p>
    {% endif %}
{%  endblock %}

shop/templates/shop/parttype_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
    <h1>Category List</h1>
    {% if parttype_list %}
        <ul>
        {% for parttype in parttype_list %}
            <li>
                <a href="{{ parttype.get_absolute_url }}">{{ parttype.name }}</a>
            </li>
        </ul>
        {% endfor %}
    {% else %}
        <p>There are currently no categories in our shop.</p>
    {% endif %}
{%  endblock %}